### ISSUE TITLE
problems in zsh after suspending emacs

### ISSUE THREAD

**Issue by curiousier-george** [benjaminor/kkp#10]
After suspending emacs, then control-C in zsh produces the character sequence 9;5u (and other control characters produce similar sequences). I don't know all the details of kkp, but I suspect it's because the Kitty Keyboard Protocol doesn't get turned off when emacs is suspended?

**Comment by benjaminor** [comment]
Hi, thanks for reporting the issue. I could not reproduce it, but from your descriptions it sounds very much like the terminal still has KKP activated when emacs is suspended.

I pushed a commit which could be a potential solution. However as I couldn't reproduce your issue, I was not able to verify the fix. Could you try the latest commit on master and report back if this solves it?

**Comment by curiousier-george** [comment]
Yes, great, it works for me so far.

Thank you so much!
