### ISSUE TITLE
Issue about "key sequece" when open org file.

### ISSUE THREAD

**Issue by bommbo** [benjaminor/kkp#3]
Some message display in minibuffer when open org file . Just org file.  
![Screenshot from 2023-03-20 20-18-52](https://user-images.githubusercontent.com/61496351/226337619-8d3daac9-b652-45e2-8bea-16f0ceffced1.png)

# version
GNU Emacs 29.0.60
kitty 0.27.1

# configuration
```
(require 'use-package)
(use-package kkp)
(use-package meow)
(require 'kkp)
(global-kkp-mode 1)
(require 'meow)
(meow-global-mode t)
```

**Comment by bommbo** [comment]
and without meow.
# open other file
C-h l
```
ESC [ ? 0 u ESC [ 1 0 4 ; 5 u l ;; view-lossage

ESC [ ? 0 u ESC [ 1 2 0 ; 3 u ;; execute-extended-command
```
# open org file
C-h l
```
ESC [ ? 0 u ESC [ ? 0 u ESC [ 1 0 4 ; 5 u l ;; view-lossage

ESC [ ? 0 u ESC [ ? 0 u ESC [ 1 2 0 ; 3 u ;; execute-extended-command

```

**Comment by DogLooksGood** [comment]
Try disable `meow-esc-mode`.

**Comment by bommbo** [comment]
> Try disable `meow-esc-mode`.

 yeah... It's fine.
